#!/usr/bin/env node
/**
 * Print a scoring prompt for a layer MDX, or append a score result
 * to audit/LAYER_SCORES.md.
 *
 * Mirrors the same in-session pattern as audit/extract/extract.mjs
 * and audit/verify/verify_entailment.mjs: this script does not call
 * an LLM. The agent reads the printed prompt, produces a JSON score,
 * then runs `node audit/score_layer.mjs append <slug>` with the
 * JSON on stdin to commit the result.
 *
 * Usage:
 *   node audit/score_layer.mjs prompt <slug>          # print scoring prompt
 *   node audit/score_layer.mjs prompt --all           # print prompts for all 15 layers
 *   node audit/score_layer.mjs append <slug>          # append the JSON on stdin to LAYER_SCORES.md
 *   node audit/score_layer.mjs summary                # render the running grades table
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const LAYERS_DIR = resolve(ROOT, "src/content/layers");
const RUBRIC_PATH = resolve(__dirname, "EDITORIAL_RUBRIC.md");
const SCORES_PATH = resolve(__dirname, "LAYER_SCORES.md");

function readLayerMdx(slug) {
  const path = resolve(LAYERS_DIR, `${slug}.mdx`);
  if (!existsSync(path)) throw new Error(`No layer MDX at ${path}`);
  return readFileSync(path, "utf8");
}

function listLayerSlugs() {
  return readdirSync(LAYERS_DIR)
    .filter((f) => f.endsWith(".mdx"))
    .map((f) => f.replace(/\.mdx$/, ""))
    .sort();
}

function printPrompt(slug) {
  const rubric = readFileSync(RUBRIC_PATH, "utf8");
  const mdx = readLayerMdx(slug);
  const wordCount = mdx
    .replace(/^---[\s\S]+?---\n/, "")
    .replace(/<[^>]+>/g, "")
    .split(/\s+/)
    .filter(Boolean).length;
  console.log(`==============================================================`);
  console.log(`SCORE LAYER: ${slug}    (current word count: ${wordCount})`);
  console.log(`==============================================================`);
  console.log("");
  console.log("RUBRIC (read this first):");
  console.log("");
  console.log(rubric);
  console.log("");
  console.log(`==============================================================`);
  console.log(`LAYER MDX (src/content/layers/${slug}.mdx):`);
  console.log(`==============================================================`);
  console.log("");
  console.log(mdx);
  console.log("");
  console.log(`==============================================================`);
  console.log(`YOUR JOB`);
  console.log(`==============================================================`);
  console.log("");
  console.log(
    "Score the layer above against each of the ten rubric criteria.",
  );
  console.log("");
  console.log(
    "Output ONE JSON object with this shape, no surrounding prose:",
  );
  console.log("");
  console.log(JSON.stringify(
    {
      slug,
      scored_at: "YYYY-MM-DD",
      scores: {
        boundary_clarity: { score: 0, evidence: "...", fix: "..." },
        no_category_errors: { score: 0, evidence: "...", fix: "..." },
        primary_sources: { score: 0, evidence: "...", fix: "..." },
        open_closed_posture: { score: 0, evidence: "...", fix: "..." },
        named_players: { score: 0, evidence: "...", fix: "..." },
        editorial_tension: { score: 0, evidence: "...", fix: "..." },
        voice_compliance: { score: 0, evidence: "...", fix: "..." },
        depth: { score: 0, evidence: "...", fix: "..." },
        glossary_integration: { score: 0, evidence: "...", fix: "..." },
        probe_primer_alignment: { score: 0, evidence: "...", fix: "..." },
      },
      total: 0,
      grade: "A | B | C | D | F",
      top_three_fixes: [
        "1. concrete edit, with paragraph reference",
        "2. concrete edit, with paragraph reference",
        "3. concrete edit, with paragraph reference",
      ],
    },
    null,
    2,
  ));
  console.log("");
  console.log(
    "Then pipe that JSON into: node audit/score_layer.mjs append " + slug,
  );
  console.log("");
}

function appendFromStdin(slug) {
  const data = readFileSync(0, "utf8").trim();
  let parsed;
  try {
    parsed = JSON.parse(data);
  } catch (e) {
    console.error(`[score_layer] could not parse JSON: ${e.message}`);
    process.exit(1);
  }
  if (parsed.slug && parsed.slug !== slug) {
    console.warn(
      `[score_layer] slug mismatch: provided ${slug}, JSON says ${parsed.slug}. Using ${slug}.`,
    );
  }
  parsed.slug = slug;
  let existing = "";
  if (existsSync(SCORES_PATH)) existing = readFileSync(SCORES_PATH, "utf8");
  if (!existing.includes("# Layer scores")) {
    existing =
      "# Layer scores\n\nGenerated by `audit/score_layer.mjs`. See `audit/EDITORIAL_RUBRIC.md` for criteria.\n\n";
  }
  // Remove any prior entry for this slug; the latest wins.
  const fence = `<!-- LAYER:${slug} -->`;
  const endFence = `<!-- /LAYER:${slug} -->`;
  const start = existing.indexOf(fence);
  if (start !== -1) {
    const end = existing.indexOf(endFence, start);
    if (end !== -1) {
      existing =
        existing.slice(0, start).trimEnd() +
        "\n\n" +
        existing.slice(end + endFence.length).trimStart();
    }
  }
  const block = renderBlock(parsed);
  existing = existing.trimEnd() + "\n\n" + block + "\n";
  writeFileSync(SCORES_PATH, existing);
  console.log(`[score_layer] appended score for ${slug} -> ${SCORES_PATH}`);
}

function renderBlock(parsed) {
  const rows = Object.entries(parsed.scores ?? {})
    .map(
      ([k, v]) =>
        `| ${k.replace(/_/g, " ")} | ${v.score}/5 | ${escape(v.evidence)} | ${escape(v.fix)} |`,
    )
    .join("\n");
  const fixes = (parsed.top_three_fixes ?? [])
    .map((f, i) => `${i + 1}. ${f.replace(/^\d+\.\s*/, "")}`)
    .join("\n");
  return [
    `<!-- LAYER:${parsed.slug} -->`,
    `## ${parsed.slug}  (${parsed.total}/50 · ${parsed.grade})`,
    ``,
    `Scored: ${parsed.scored_at}`,
    ``,
    `| Criterion | Score | Evidence | Fix |`,
    `|---|---|---|---|`,
    rows,
    ``,
    `**Top fixes:**`,
    ``,
    fixes,
    `<!-- /LAYER:${parsed.slug} -->`,
  ].join("\n");
}

function escape(s) {
  return String(s ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\n/g, " ");
}

function summary() {
  if (!existsSync(SCORES_PATH)) {
    console.log("(no scores yet — run `prompt <slug>` and `append <slug>`)");
    return;
  }
  const text = readFileSync(SCORES_PATH, "utf8");
  const headers = [...text.matchAll(/^## (\S+)\s+\((\d+)\/50 · ([A-F])\)/gm)];
  console.log(`# Layer scores summary\n`);
  console.log(`| Layer | Score | Grade |`);
  console.log(`|---|---|---|`);
  for (const m of headers.sort((a, b) => Number(b[2]) - Number(a[2]))) {
    console.log(`| ${m[1]} | ${m[2]}/50 | ${m[3]} |`);
  }
  console.log(
    `\n${headers.length} of ${listLayerSlugs().length} layers scored.`,
  );
}

const [cmd, arg] = process.argv.slice(2);
if (cmd === "prompt" && arg === "--all") {
  for (const slug of listLayerSlugs()) printPrompt(slug);
} else if (cmd === "prompt" && arg) {
  printPrompt(arg);
} else if (cmd === "append" && arg) {
  appendFromStdin(arg);
} else if (cmd === "summary") {
  summary();
} else {
  console.log("usage: node audit/score_layer.mjs <prompt|append|summary> [slug|--all]");
  process.exit(1);
}
