#!/usr/bin/env node
/**
 * Coverage check: compare every YAML data file against the canonical
 * lists in audit/completeness/{projects,funders,concepts}_canonical.json
 * and surface anything in the canonical list that is NOT in the YAML.
 *
 * Writes audit/CONCEPTS_INDEX.md with the rendered coverage status.
 *
 * Exits 0 always (this is informational, not a build gate). A
 * scheduled monthly routine reads the output and decides what to
 * triage.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");

function loadYaml(rel) {
  return yaml.load(readFileSync(resolve(ROOT, rel), "utf8"));
}
function loadJson(rel) {
  return JSON.parse(readFileSync(resolve(ROOT, rel), "utf8"));
}

// ----- Projects -----
const projectsCanonical = loadJson("audit/completeness/projects_canonical.json");
const projectsYaml = loadYaml("data/projects.yaml").projects;
const projectSlugs = new Set(projectsYaml.map((p) => p.slug));

const projectsCovered = [];
const projectsMissing = [];
for (const entry of projectsCanonical.projects) {
  const inYaml = projectSlugs.has(entry.slug);
  if (inYaml) {
    projectsCovered.push(entry);
  } else {
    projectsMissing.push(entry);
  }
}

// ----- Funders + concepts: optional; render placeholders if files exist -----
function maybeLoadCanonical(name) {
  const path = resolve(__dirname, `${name}_canonical.json`);
  if (!existsSync(path)) return null;
  return loadJson(`audit/completeness/${name}_canonical.json`);
}

const fundersCanonical = maybeLoadCanonical("funders");
const conceptsCanonical = maybeLoadCanonical("concepts");

// ----- Render CONCEPTS_INDEX.md -----
const today = new Date().toISOString().slice(0, 10);
const lines = [];
lines.push("# Concepts Index (Coverage)");
lines.push("");
lines.push("This file is the recall artifact. For each entity the");
lines.push("site SHOULD cover (per the canonical lists in");
lines.push("`audit/completeness/`), it shows the coverage status.");
lines.push("");
lines.push("Generated by `audit/completeness/check_coverage.mjs`; do");
lines.push("not edit by hand. To change what's tracked, edit the");
lines.push("canonical JSON files.");
lines.push("");
lines.push(`Last refreshed: ${today}`);
lines.push("");

// Projects section.
lines.push("## Projects");
lines.push("");
lines.push(`Canonical: ${projectsCanonical.projects.length} entries. Site coverage: ${projectsCovered.length} of ${projectsCanonical.projects.length} (${Math.round((100 * projectsCovered.length) / projectsCanonical.projects.length)}%).`);
lines.push("");

if (projectsMissing.length > 0) {
  lines.push("### Missing from data/projects.yaml");
  lines.push("");
  lines.push("| Slug | Layer | Priority | Note |");
  lines.push("|---|---|---|---|");
  for (const e of projectsMissing.sort((a, b) => {
    const order = { high: 0, medium: 1, low: 2 };
    return (order[a.priority] ?? 9) - (order[b.priority] ?? 9);
  })) {
    lines.push(`| ${e.slug} | ${e.layer} | ${e.priority} | ${e.note ?? "in_yaml=false in canonical"} |`);
  }
  lines.push("");
} else {
  lines.push("### Missing from data/projects.yaml");
  lines.push("");
  lines.push("None. Every canonical project is in the YAML.");
  lines.push("");
}

// Covered, grouped by layer.
lines.push("### Covered, by layer");
lines.push("");
const byLayer = {};
for (const e of projectsCovered) {
  if (!byLayer[e.layer]) byLayer[e.layer] = [];
  byLayer[e.layer].push(e);
}
for (const layer of Object.keys(byLayer).sort()) {
  lines.push(`- **${layer}** (${byLayer[layer].length}): ${byLayer[layer].map((e) => e.slug).join(", ")}`);
}
lines.push("");

// Funders section (placeholder).
lines.push("## Funders");
lines.push("");
if (fundersCanonical) {
  // TODO: same comparison once funders_canonical.json exists.
  lines.push("(Funders canonical list present; full coverage check coming.)");
} else {
  lines.push("Canonical funders list not yet populated. See the existing");
  lines.push("`scripts/grants-discovery.md` routine which serves a");
  lines.push("similar purpose for funders + grants today.");
}
lines.push("");

// Concepts section (placeholder).
lines.push("## Concepts");
lines.push("");
if (conceptsCanonical) {
  lines.push("(Concepts canonical list present; full coverage check coming.)");
} else {
  lines.push("Canonical concepts list not yet populated. This will track");
  lines.push("load-bearing concepts in the open-source-AI conversation");
  lines.push("(e.g. \"speculative decoding\", \"FlashAttention\", \"DiLoCo\")");
  lines.push("that don't have their own entry but probably should be");
  lines.push("mentioned in some layer page or essay.");
}
lines.push("");

writeFileSync(resolve(ROOT, "audit/CONCEPTS_INDEX.md"), lines.join("\n"));
console.log(`[check_coverage] CONCEPTS_INDEX.md updated`);
console.log(`[check_coverage] projects: ${projectsCovered.length}/${projectsCanonical.projects.length} covered, ${projectsMissing.length} missing`);
